// Code generated by MockGen. DO NOT EDIT.
// Source: bridge.go
//
// Generated by this command:
//
//	mockgen -source=bridge.go -package=mock_macos -destination=./mock/mock_bridge.go
//

// Package mock_macos is a generated GoMock package.
package mock_macos

import (
	reflect "reflect"

	macos "github.com/jackchuka/dutix/internal/macos"
	gomock "go.uber.org/mock/gomock"
)

// MockBridge is a mock of Bridge interface.
type MockBridge struct {
	ctrl     *gomock.Controller
	recorder *MockBridgeMockRecorder
	isgomock struct{}
}

// MockBridgeMockRecorder is the mock recorder for MockBridge.
type MockBridgeMockRecorder struct {
	mock *MockBridge
}

// NewMockBridge creates a new mock instance.
func NewMockBridge(ctrl *gomock.Controller) *MockBridge {
	mock := &MockBridge{ctrl: ctrl}
	mock.recorder = &MockBridgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBridge) EXPECT() *MockBridgeMockRecorder {
	return m.recorder
}

// GetDefaultAppForScheme mocks base method.
func (m *MockBridge) GetDefaultAppForScheme(scheme string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultAppForScheme", scheme)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultAppForScheme indicates an expected call of GetDefaultAppForScheme.
func (mr *MockBridgeMockRecorder) GetDefaultAppForScheme(scheme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultAppForScheme", reflect.TypeOf((*MockBridge)(nil).GetDefaultAppForScheme), scheme)
}

// GetDefaultAppForUTI mocks base method.
func (m *MockBridge) GetDefaultAppForUTI(uti string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultAppForUTI", uti)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultAppForUTI indicates an expected call of GetDefaultAppForUTI.
func (mr *MockBridgeMockRecorder) GetDefaultAppForUTI(uti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultAppForUTI", reflect.TypeOf((*MockBridge)(nil).GetDefaultAppForUTI), uti)
}

// ListAllApplications mocks base method.
func (m *MockBridge) ListAllApplications() ([]macos.AppInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllApplications")
	ret0, _ := ret[0].([]macos.AppInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllApplications indicates an expected call of ListAllApplications.
func (mr *MockBridgeMockRecorder) ListAllApplications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllApplications", reflect.TypeOf((*MockBridge)(nil).ListAllApplications))
}

// ListAppsForScheme mocks base method.
func (m *MockBridge) ListAppsForScheme(scheme string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAppsForScheme", scheme)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAppsForScheme indicates an expected call of ListAppsForScheme.
func (mr *MockBridgeMockRecorder) ListAppsForScheme(scheme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAppsForScheme", reflect.TypeOf((*MockBridge)(nil).ListAppsForScheme), scheme)
}

// ListAppsForUTI mocks base method.
func (m *MockBridge) ListAppsForUTI(uti string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAppsForUTI", uti)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAppsForUTI indicates an expected call of ListAppsForUTI.
func (mr *MockBridgeMockRecorder) ListAppsForUTI(uti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAppsForUTI", reflect.TypeOf((*MockBridge)(nil).ListAppsForUTI), uti)
}

// ListDefaultDocumentTypesForApp mocks base method.
func (m *MockBridge) ListDefaultDocumentTypesForApp(appPath string) ([]macos.DocumentType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefaultDocumentTypesForApp", appPath)
	ret0, _ := ret[0].([]macos.DocumentType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefaultDocumentTypesForApp indicates an expected call of ListDefaultDocumentTypesForApp.
func (mr *MockBridgeMockRecorder) ListDefaultDocumentTypesForApp(appPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefaultDocumentTypesForApp", reflect.TypeOf((*MockBridge)(nil).ListDefaultDocumentTypesForApp), appPath)
}

// ListSupportedDocumentTypes mocks base method.
func (m *MockBridge) ListSupportedDocumentTypes(appPath string) ([]macos.DocumentType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSupportedDocumentTypes", appPath)
	ret0, _ := ret[0].([]macos.DocumentType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSupportedDocumentTypes indicates an expected call of ListSupportedDocumentTypes.
func (mr *MockBridgeMockRecorder) ListSupportedDocumentTypes(appPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSupportedDocumentTypes", reflect.TypeOf((*MockBridge)(nil).ListSupportedDocumentTypes), appPath)
}

// ResolveUTIsForExtension mocks base method.
func (m *MockBridge) ResolveUTIsForExtension(ext string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUTIsForExtension", ext)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUTIsForExtension indicates an expected call of ResolveUTIsForExtension.
func (mr *MockBridgeMockRecorder) ResolveUTIsForExtension(ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUTIsForExtension", reflect.TypeOf((*MockBridge)(nil).ResolveUTIsForExtension), ext)
}

// SetDefaultForScheme mocks base method.
func (m *MockBridge) SetDefaultForScheme(appPath, scheme string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultForScheme", appPath, scheme)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultForScheme indicates an expected call of SetDefaultForScheme.
func (mr *MockBridgeMockRecorder) SetDefaultForScheme(appPath, scheme any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultForScheme", reflect.TypeOf((*MockBridge)(nil).SetDefaultForScheme), appPath, scheme)
}

// SetDefaultForUTI mocks base method.
func (m *MockBridge) SetDefaultForUTI(appPath, uti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultForUTI", appPath, uti)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultForUTI indicates an expected call of SetDefaultForUTI.
func (mr *MockBridgeMockRecorder) SetDefaultForUTI(appPath, uti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultForUTI", reflect.TypeOf((*MockBridge)(nil).SetDefaultForUTI), appPath, uti)
}
